#pragma config(UART_Usage, UART1, uartVEXLCD, baudRate19200, IOPins, None, None)
#pragma config(Sensor, in1,    PowerExpander,  sensorNone)
#pragma config(Sensor, in2,    LiftPotRight,   sensorPotentiometer)
#pragma config(Sensor, in3,    LiftPotLeft,    sensorPotentiometer)
#pragma config(Sensor, in4,    MobileGoalPot,  sensorPotentiometer)
#pragma config(Sensor, dgtl1,  RightGoalLiftLim, sensorTouch)
#pragma config(Sensor, dgtl2,  LeftGoalLiftLim, sensorTouch)
#pragma config(Sensor, dgtl3,  LeftGoalLiftBtn, sensorTouch)
#pragma config(Sensor, dgtl4,  RightGoalLiftBtn, sensorTouch)
#pragma config(Sensor, dgtl7,  LeftDriveQuad,  sensorQuadEncoder)
#pragma config(Sensor, dgtl9,  RightDriveQuad, sensorQuadEncoder)
#pragma config(Motor,  port2,           MobileGoalLift, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           FlipperRight,  tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           RDrive_A,      tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port5,           LiftOne_B,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           LiftTwo_C,     tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port7,           LDrive_D,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           Grabber,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           Flipper,       tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//copy of lcd config in case deleted
//#pragma config(UART_Usage, UART1, uartVEXLCD, baudRate19200, IOPins, None, None)

//Competition Control and Duration Settings
#pragma competitionControl(Competition)
#pragma autonomousDuration(15)
#pragma userControlDuration(250)
#include "Vex_Competition_Includes.c"

/********************************/
////////DECLARE GLOBAL VARS///////
/********************************/

//exponent macro

#define pow( x,a ) ( exp((a)*log(x)) );

//Declare Button Vars

int timer = 0;
int btn5d = 0;
int btn5u = 0;
int btn6d = 0;
int btn6u = 0;
int btn8d = 0;
int btn8u = 0;
int btn8l = 0;
int btn8r = 0;
int btn7d = 0;
int btn7u = 0;
int btn7l = 0;
int btn7r = 0;

//
//

int lift_one;
int lift_two;
int slewCount = 0;
int slewDelay = 10; // sleep time in millseconds between motor power updates (50ms = 1s delay from 0-100)
int motorSetpoint[10];
int GLPot;
int GLStoreVar[6];
string mainBattery, backupBattery, expanderBattery;
int hold = 0;
int holding = 0;
int toggleHold = 0;
int posLeft;
int posRight;
int rightAdjust = 2;
int lastPosLeft;
int lastPosRight;
int liftStabIntegral;
int temp_one;
int temp_two;
int temp_three;
int weight;
int average;
int LCDControl;
int expoFlip;
int expoLift;
int quadRight;
int quadLeft;
int liftErrorAdjust = 0;
bool liftAuton = false;
bool stacking = false;
bool goalManual;

/*****************************/
///////DECLARE FUNCTIONS///////
/*****************************/

#include "..\VexRobotCLibraries\Robot1_2017-2018_Functions.h"
#include "..\VexRobotCLibraries\Robot1_2017-2018_Auton.h"

/*****************/
///////MAIN////////
/*****************/
task usercontrol() {
	goalManual = true
	bLCDBacklight = true; // Turn on LCD Backlight
	presetMotorSetpoints();
	initGLVar();
	liftAuton = false;
	startTask(Slew);
	startTask(Lift);
	startTask(LCD);
	startTask(LCDSelect);
	while(1) {
		if(!stacking){
			Buttons();
			Drive();
			GoalLift();
			holdLift();
			claw();
			flip();
			if(btn7l && btn8d) {
				stacking = true;
			}
		}else {
			while(btn7l || btn8d){
				Buttons();
			};
			startTask(stack);
			while(stacking){
				abort();
				sleep(100);
			};
		}
	}
}


/****************/
//////AUTON///////
/****************/

void pre_auton() {
}

task autonomous() {
	initializeQuadEncoders();
	weight = 0;
	liftPID = 0;
	presetMotorSetpoints();
	startTask(Slew);
	startTask(Lift);
	startTask(AutonDrivePID);
	startTask(AutonGoalLift);
	startTask(ChainBar);
	liftAuton = true;
	if(SensorValue[PowerExpander]*3.537/1000.0 < 5) {
		displayNextLCDString("Expander Low");
		}else if(SelectedAuton == 2) {
		displayLCDCenteredString(0, "Autonomous 2");
		AutonTwo();
		}else if(SelectedAuton == 3) {
		displayLCDCenteredString(0, "Autonomous 3");
		AutonThree();
		}else if(SelectedAuton == 4) {
		displayLCDCenteredString(0, "Autonomous 4");
		AutonFour();
		}else {
		displayLCDCenteredString(0, "Autonomous 1");
			AutonOne();
			//AutonTwo();
			//AutonThree();
			//AutonTest();
		}
}
